services:
  app:
    build:
      context: .
      dockerfile: .lenra/Dockerfile
      # cache_from:
      # - lenra/app:cache
      # - type=local,src=./.lenra/dockercache
      # cache_to: 
      # - lenra/app:cache
      # - type=local,dest=./.lenra/dockercache
    depends_on:
      - devtools
      # devtools:
      #   condition: service_healthy
  devtools:
    image: lenra/devtools
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenra_devtool
      POSTGRES_HOST: postgres
      OF_WATCHDOG_BIN: sh
    depends_on:
      - postgres
    ports:
      - "4000"
    # networks:
    #   lenra-app:
    #     aliases:
    #       - api.lenra.io
    #   lenra: {}
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenra_devtool
    # networks:
    #   - lenra

# networks:
#   lenra-app: {}
#   lenra: {}