componentsApi: "1.1"
builders:
  - name: builder
    image: ekidd/rust-musl-builder
    copySources: true
    user: rust
    cache:
      - /usr/local/cargo/registry
      # - /home/rust/src/target
    script:
      - cargo build --release
image: scratch
artifacts:
  - builder: builder
    source: /home/rust/src/target/x86_64-unknown-linux-musl/release/template-rust
    destination: /app
watchdog:
  targetDir: /
  params:
    fprocess: /app
