componentsApi: "1.1"
debug:
  image: rust
  run: rust-gdb /home/rust/src/target/release/template-rust
  
release:
  builders:
    - name: builder
      image: ekidd/rust-musl-builder
      copy:
        - "*"
      cache:
        - /usr/local/cargo/registry
        # - /home/rust/src/target
      script:
        - cargo build --release
  image: scratch
  artifacts:
    - builder: builder
      source: /home/rust/src/target/x86_64-unknown-linux-musl/release/template-rust
      destination: /app
  run: /app
  ignore:
    - target
